### ISSUE TITLE
Is this for using PCOV with PHPUnit 7?

### ISSUE THREAD

**Issue by swashata** [krakjoe/pcov-clobber#1]
Hello,

Sorry for maybe asking a very naive question. I just got a tweet https://twitter.com/s_bergmann/status/1142343736078282752 and trying to get my head around it.

### A bit of history

I understand that pcov is something that I install with `pecl`, much like `xdebug` and enable from `php.ini` file. Up to this is clear for me.

I also understand that somehow, PCOV support was added to PHPUnit 8 only. But I am stuck using PHPUnit 7, because I am writing a WordPress plugin and the WP integration testing lib, doesn't yet support PHPUnit 8.

### Question

So here are the questions

1. Is this composer package for somehow fiddling the built-in PHPUnit 7 XDebug driver to use PCOV instead?
2. It says on README, that pcov bin is also installed. Does it mean, I don't need to `pecl install pcov` and perhaps edit `php.ini`?
3. After I require this composer package and do a `vendor/bin/pcov clobber`, will PHPUnit 7 just work out of the box? Or do I need to change anything?

Thank you for your time and effort you've put into this. I am just trying to understand how things fit together.

**Comment by krakjoe** [comment]
For PHPUnit to use PCOV, you have to install it with pecl, and load it with ini.

For PHPUnit versions below 8, you have to additionally install this package. Instructions for usage are found in the readme.

If at all possible, upgrade to PHPUnit 8 ...

**Comment by swashata** [comment]
Thanks. I will give it a go. I cannot upgrade to PHPUnit 8 because WP test libs don't support that yet.

**Comment by ktamas77** [comment]
Is there a way to make it work with PHPUnit 5?
I can start working on it if it's possible to help with this project, to create a driver patch...
If it's not even possible to make it work with PHPUnit 5, please let me know.
